FROM ruby:2.6.5

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs postgresql-client

RUN mkdir /sugomori-api
WORKDIR /sugomori-api
COPY Gemfile /sugomori-api/Gemfile
COPY Gemfile.lock /sugomori-api/Gemfile.lock
RUN gem install bundler
RUN bundle install

RUN apt-get update && apt-get install -y curl apt-transport-https wget && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update && apt-get install -y yarn
ADD . /sugomori-api

